# **Working 2D Arrays With Numpy**

In [34]:
import numpy as np

**The basics and Array Creation in 2D**

Creating a 2D array from a nested list

In [22]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Dimensions

In [23]:
arr.ndim

2

Size

In [24]:
arr.size

9

Shape

In [25]:
arr.shape

(3, 3)

Creating a 2D array filled with zeros

In [26]:
arr_zeros = np.zeros((3, 4))
print(arr_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Creating a 2D array filled with ones

In [27]:
arr_ones = np.ones((2, 3))
print(arr_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


Creating a 2D identity matrix

In [28]:
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Indexing and Slicing in 2D**

In [29]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

Accesing individual elements

In [30]:
print(arr[0, 0])
print(arr[1, 2])

1
6


Slicing a subarray

In [31]:
print(arr[1:, :2])

[[4 5]
 [7 8]]


Boolean indexing

In [16]:
mask = arr > 5
print(arr[mask])

[6 7 8 9]


In [32]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Define a custom condition function
def condition(x):
    return x % 2 == 0

# Apply the condition function to the array
mask = condition(arr)

# Filter the elements using the boolean mask
filtered_arr = arr[mask]

print(filtered_arr)

[2 4 6 8]
